# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonasHasLugares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('status', models.CharField(choices=[('1', 'Actual'), ('0', 'Ya no')], max_length=20)),
                ('lugares_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugares.Lugares')),
                ('personas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Personas')),
            ],
        ),
    ]
